### ISSUE TITLE
Execution failed for task ':test'

### ISSUE THREAD

**Issue by labhane** [ministryofjustice/pdf-generator#51]
:processTestResources
:testClasses
:test

ParoleParom1ReportTest > Delius user does not enter any text into the free text fields FAILED
    org.spockframework.runtime.ConditionNotSatisfiedError at ParoleParom1ReportTest.groovy:934

101 tests completed, 1 failed
:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///C:/Users/USER/Downloads/pdf-generator-master/pdf-generator-master/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3 mins 8.943 secs

**Comment by theDustRoom** [comment]
All tests currently pass successfully and as this issue was raised so long ago I will close this.
